var lessons = [
  {
    id: 1001,
    title: "Game Development",
    location: "Middlesex University Dubai - Block 19",
    description:
      "Learn how to use unreal engine to develop your own video game of any genre!",
    price: 20.0,
    image: "images/game.webp",
    availableInventory: 4,
    rating: 4,
  },
  {
    id: 1002,
    title: "Photography",
    location: "Middlesex University Dubai - Block 17",
    description:
      "Study how to capture some of the most breath taking moments you'll ever witness in all of their glory.",
    price: 40.0,
    image: "images/photography.jpg",
    availableInventory: 8,
    rating: 4,
  },
  {
    id: 1003,
    title: "Dance",
    location: "University of Wollongong in Dubai",
    description:
      "Feel like your body has to flow with the music as well as your mind does? Take up the dance classes. Numerous categories to choose from including hip hop and ballet!",
    price: 50.5,
    image: "images/dance.avif",
    availableInventory: 2,
    rating: 5,
  },
  {
    id: 1004,
    title: "Culinary",
    location: "International Centre for Culinary Arts Abu Dhabi",
    description:
      "Have skills and recipes taught to you by guest celebrity and michelin chefs from around the world!",
    price: 100.0,
    image: "images/culinary.webp",
    availableInventory: 5,
    rating: 5,
  },
  {
    id: 1005,
    title: "Film Production",
    location: "Middlesex University Dubai - Block 17",
    description:
      "Create your own amazing content with the camera work and video editing taught in this class.",
    price: 80.0,
    image: "images/film.jpg",
    availableInventory: 8,
    rating: 4,
  },
  {
    id: 1006,
    title: "Martial Arts",
    location: "The Warrior Academy Dubai",
    description:
      "Learn self defense using karate, judo, taekwondo, and more martial arts which you can choose from",
    price: 60.5,
    image: "images/martialarts.jpg",
    availableInventory: 6,
    rating: 5,
  },
  {
    id: 1007,
    title: "DIY & Crafts",
    location: "PursueIt - Dubai",
    description:
      "Create projects by building, crafting, and creating items to your liking.",
    price: 35.0,
    image: "images/diy.webp",
    availableInventory: 3,
    rating: 4,
  },
  {
    id: 1008,
    title: "Yoga",
    location: "YogaOne - Abu Dhabi",
    description: "Achieve Zen by practicing mindfulness and relaxation.",
    price: 20.0,
    image: "images/yoga.jpg",
    availableInventory: 9,
    rating: 3,
  },
  {
    id: 1009,
    title: "Music",
    location: "Solid Rock - Dubai",
    description:
      "Learn how to play different instruments or sing by joining the different clubs created within this extracurricular activity, initiated by the different ideas of students themselves!",
    price: 40.0,
    image: "images/music.jpg",
    availableInventory: 6,
    rating: 4,
  },
  {
    id: 1010,
    title: "Cybersecurity",
    location: "Middlesex University Dubai - Block 19",
    description:
      "Start taking more control of your digital footprint and security by learning how to protect your computer through this cybersecurity course. We have different events every week!",
    price: 30.0,
    image: "images/IT.avif",
    availableInventory: 7,
    rating: 3,
  },
];
